title: Marilyn L. Logwood
description: Machine learning analysis of the Relationship Between Volume and Volatility in Selected Dow Jones Stocks
logo: /assets/IMG/template_logo.png
show_downloads: true
theme: jekyll-theme-minima
